repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff lint
        entry: .venv/bin/ruff check . --exclude=.venv 
        language: system
        pass_filenames: false
        verbose: true 

      - id: ruff-format
        name: Ruff format
        entry: .venv/bin/ruff format --check . --exclude=.venv
        language: system
        pass_filenames: false
        verbose: true 

      - id: mypy
        name: Mypy
        entry: .venv/bin/mypy . --exclude=.venv
        language: system
        pass_filenames: false
        verbose: true 