version: 2.1
jobs:
    build:
        docker:
            - image: cimg/python:3.12.7
        steps: 
            - checkout
            - run:
                name: Install Dependencies 
                command: | 
                    python -m venv .venv
                    source .venv/bin/activate
                    python -m pip install -r requirements.txt
            - run:
                name: Linting
                command: | 
                    source .venv/bin/activate
                    ruff check . --exclude=.venv
            - run:
                name: Formatting
                command: | 
                    source .venv/bin/activate
                    ruff format --check . --exclude=.venv
            - run:
                name: Type Hinting
                command: | 
                    source .venv/bin/activate
                    mypy . --exclude=.venv  
            - run:
                name: Define Environment Variable at Runtime
                command: | 
                    echo ' export "APCA-API-KEY-ID" = os.environ["APCA_API_KEY_ID"] ' >> '$BASH_ENV'
                    echo ' export "APCA-API-SECRET-KEY" = os.environ["APCA-API-SECRET-KEY"] ' >> '$BASH_ENV'
            - run:
                name: Run Tests
                command: |
                    source .venv/bin/activate
                    python -m pytest -v tests/test_main.py

workflows:
    build:
        jobs:
            - build