name: CI

on: 
  push: 
    branches:
      - main

jobs:
  build-and-test:
    name: Lint, type-check & test (Python 3.13)
    runs-on: ubuntu-latest
    env:
      APCA_API_KEY_ID: ${{ secrets.APCA_API_KEY_ID }}
      APCA_API_SECRET_KEY: ${{ secrets.APCA_API_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: 3.13
      - run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install -r requirements.txt
          ruff check . --exclude=.venv
          ruff format --check . --exclude=.venv
          mypy . --exclude=.venv
          pytest -v --cov=main tests/test_main.py


  
        

